#ifndef CBM_LSP_PY_LSP_H
#define CBM_LSP_PY_LSP_H

#include "type_rep.h"
#include "scope.h"
#include "type_registry.h"
#include "../cbm.h"
#include "go_lsp.h"  // CBMLSPDef, CBMResolvedCallArray reused across languages

// PyLSPContext holds state for one Python file's type evaluation.
typedef struct {
    CBMArena* arena;
    const char* source;
    int source_len;
    const CBMTypeRegistry* registry;
    CBMScope* current_scope;

    // Import map: local_name -> module_qn (arena-allocated, NULL-terminated).
    // Built from CBMFileResult.imports.
    const char** import_local_names;
    const char** import_module_qns;
    int import_count;

    // Current function/class context for resolving `self`/`cls` and emitting
    // caller QNs.
    const char* enclosing_func_qn;
    const char* enclosing_class_qn;
    const char* module_qn;

    // Output: resolved calls accumulate here.
    CBMResolvedCallArray* resolved_calls;

    // Debug mode (CBM_LSP_DEBUG env, shared across all language LSPs).
    bool debug;
} PyLSPContext;

// Initialize a PyLSPContext for processing one file.
void py_lsp_init(PyLSPContext* ctx, CBMArena* arena, const char* source, int source_len,
    const CBMTypeRegistry* registry, const char* module_qn, CBMResolvedCallArray* out);

// Add an import mapping (call once per CBMImport entry).
void py_lsp_add_import(PyLSPContext* ctx, const char* local_name, const char* module_qn);

// Process all functions/classes in a file's AST, evaluating types and resolving calls.
// root must be the tree-sitter Python `module` node.
void py_lsp_process_file(PyLSPContext* ctx, TSNode root);

// Entry point: build registry from file's own defs + run LSP resolution.
// Mirrors cbm_run_go_lsp / cbm_run_c_lsp.
void cbm_run_py_lsp(CBMArena* arena, CBMFileResult* result,
    const char* source, int source_len, TSNode root);

// Register Python stdlib types and functions into a registry.
// Auto-generated by scripts/gen-py-stdlib.py from typeshed.
// Phase 10 fills the body; Phase 2 ships a no-op so linkage works.
void cbm_python_stdlib_register(CBMTypeRegistry* reg, CBMArena* arena);

// --- Cross-file LSP resolution ---

void cbm_run_py_lsp_cross(
    CBMArena* arena,
    const char* source, int source_len,
    const char* module_qn,
    CBMLSPDef* defs, int def_count,
    const char** import_names, const char** import_qns, int import_count,
    TSTree* cached_tree,           // NULL = parse internally
    CBMResolvedCallArray* out);

// --- Batch cross-file LSP ---

typedef struct {
    const char* source;
    int source_len;
    const char* module_qn;
    TSTree* cached_tree;           // from TSTree caching (NULL = parse internally)
    CBMLSPDef* defs;               // combined file-local + cross-file defs
    int def_count;
    const char** import_names;     // parallel arrays, import_count long
    const char** import_qns;
    int import_count;
} CBMBatchPyLSPFile;

void cbm_batch_py_lsp_cross(
    CBMArena* arena,
    CBMBatchPyLSPFile* files, int file_count,
    CBMResolvedCallArray* out);

#endif // CBM_LSP_PY_LSP_H
